/*  Copyright (C) 2013 In2 Printing Solutions <info@in2ps.com>
    Author: Jose Maria Martinez

    This program is free software; you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation; either version 3 of the License, or
    (at your option) any later version.

    This program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License along
    with this program; if not, write to the Free Software Foundation, Inc.,
    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/
/****************************************************************************
**
** Metadata for CemitecProxyOPC generated by dumpcpp from type library
** OPC_DLL_Puente.dll
**
****************************************************************************/

#define QAX_DUMPCPP_CEMITECPROXYOPC_NOINLINES
#include "cemitecproxyopc.h"

using namespace CemitecProxyOPC;

static const uint qt_meta_data_CemitecProxyOPC___CemitecObjectOPC[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       10,    10, // methods
       1,    60, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       35, 74, 96, 97, 5,
       98, 123, 128, 129, 5,
       130, 156, 171, 172, 5,

 // slots: signature, parameters, type, tag, flags
       173, 196, 215, 224, 9,
       225, 247, 256, 260, 9,
       261, 286, 306, 315, 9,
       316, 337, 338, 347, 9,
       348, 376, 395, 404, 9,
       405, 431, 444, 448, 9,
       449, 463, 476, 485, 9,

 // properties: name, type, flags
       486, 494, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_CemitecProxyOPC___CemitecObjectOPC() {
    static const char stringdata0[] = {
    "CemitecProxyOPC::_CemitecObjectOPC\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "adicionaGrupo(QString)\0ConnectedGroupName\0QVariant\0\0adicionaItem(QString)\0"
    "itemName\0int\0\0conectaServidor(QString)\0ConnectedServerName\0QVariant\0\0desconectaServidor()\0\0QVariant\0\0escribeDato(int&,QVariant&)\0clientHandle,value\0QVariant\0\0getItemServerHandle(int&)\0clientHandle\0int\0"
    "\0leeDato(int&)\0clientHandle\0QVariant\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject _CemitecObjectOPC::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_CemitecProxyOPC___CemitecObjectOPC(),
qt_meta_data_CemitecProxyOPC___CemitecObjectOPC }
};

void *_CemitecObjectOPC::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_CemitecProxyOPC___CemitecObjectOPC()))
        return static_cast<void*>(const_cast<_CemitecObjectOPC*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_CemitecProxyOPC__CemitecObjectOPC[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       11,    10, // methods
       0,    0, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       34, 95, 139, 140, 5,
       141, 180, 202, 203, 5,
       204, 229, 234, 235, 5,
       236, 262, 277, 278, 5,

 // slots: signature, parameters, type, tag, flags
       279, 302, 321, 330, 9,
       331, 353, 362, 366, 9,
       367, 392, 412, 421, 9,
       422, 443, 444, 453, 9,
       454, 482, 501, 510, 9,
       511, 537, 550, 554, 9,
       555, 569, 582, 591, 9,

        0        // eod
};

static const char *qt_meta_stringdata_CemitecProxyOPC__CemitecObjectOPC() {
    static const char stringdata0[] = {
    "CemitecProxyOPC::CemitecObjectOPC\0"
    "EvDataChange(int&,QVariantList&,QVariantList&,QVariantList&)\0NumItems,ClientHandles,ItemValues,Qualities\0\0\0exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0"
    "\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "adicionaGrupo(QString)\0ConnectedGroupName\0QVariant\0\0adicionaItem(QString)\0itemName\0int\0\0conectaServidor(QString)\0ConnectedServerName\0QVariant\0\0desconectaServidor()\0"
    "\0QVariant\0\0escribeDato(int&,QVariant&)\0clientHandle,value\0QVariant\0\0getItemServerHandle(int&)\0clientHandle\0int\0\0leeDato(int&)\0clientHandle\0QVariant\0\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject CemitecObjectOPC::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_CemitecProxyOPC__CemitecObjectOPC(),
qt_meta_data_CemitecProxyOPC__CemitecObjectOPC }
};

void *CemitecObjectOPC::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_CemitecProxyOPC__CemitecObjectOPC()))
        return static_cast<void*>(const_cast<CemitecObjectOPC*>(this));
    return QAxObject::qt_metacast(_clname);
}

static const uint qt_meta_data_CemitecProxyOPC____CemitecObjectOPC[] = {

 // content:
       1,       // revision
       0,       // classname
       0,    0, // classinfo
       4,    10, // methods
       1,    30, // properties
       0,    0, // enums/sets

 // signals: signature, parameters, type, tag, flags
       36, 75, 97, 98, 5,
       99, 124, 129, 130, 5,
       131, 157, 172, 173, 5,

 // slots: signature, parameters, type, tag, flags
       174, 235, 279, 280, 9,

 // properties: name, type, flags
       281, 289, 0x0a055003, 		 // QString control

        0        // eod
};

static const char *qt_meta_stringdata_CemitecProxyOPC____CemitecObjectOPC() {
    static const char stringdata0[] = {
    "CemitecProxyOPC::__CemitecObjectOPC\0"
    "exception(int,QString,QString,QString)\0code,source,disc,help\0\0\0propertyChanged(QString)\0name\0\0\0signal(QString,int,void*)\0name,argc,argv\0\0\0"
    "EvDataChange(int&,QVariantList&,QVariantList&,QVariantList&)\0NumItems,ClientHandles,ItemValues,Qualities\0"
    "\0\0"
    "control\0QString\0"
    };
    static char data[sizeof(stringdata0) + 0];
    if (!data[0]) {
        int index = 0;
        memcpy(data + index, stringdata0, sizeof(stringdata0) - 1);
        index += sizeof(stringdata0) - 1;
    }

    return data;
};

const QMetaObject __CemitecObjectOPC::staticMetaObject = {
{ &QObject::staticMetaObject,
qt_meta_stringdata_CemitecProxyOPC____CemitecObjectOPC(),
qt_meta_data_CemitecProxyOPC____CemitecObjectOPC }
};

void *__CemitecObjectOPC::qt_metacast(const char *_clname)
{
    if (!_clname) return 0;
    if (!strcmp(_clname, qt_meta_stringdata_CemitecProxyOPC____CemitecObjectOPC()))
        return static_cast<void*>(const_cast<__CemitecObjectOPC*>(this));
    return QAxObject::qt_metacast(_clname);
}

